[package]
name = "csgrs"
version = "0.17.0"
edition = "2024"
description = "Constructive solid geometry on meshes using BSP trees in Rust"
authors = ["Timothy Schmidt <timschmidt@gmail.com>",]
license = "MIT"
repository = "https://github.com/timschmidt/csgrs"
readme = "readme.md"

[dependencies]
core2 = { version = "0.4.0", features = ["alloc"] }
nalgebra = "0.33"
geo = { version = "0.29.3", default-features = false, features = ["earcutr"] }

geo-buf = { version = "0.1.0", optional = true } # straight-skeleton offsetting iOverlay can handle this in v2
chull = { version = "0.2.4", optional = true }
dxf = { version = "0.6.0", optional = true }
rapier3d-f64 = { version = "0.23.0", optional = true }
rapier3d = { version = "0.23.0", optional = true }
parry3d-f64  = { version = "0.18.0", optional = true }
parry3d  = { version = "0.18.0", optional = true }
rayon = { version = "1.7", optional = true }
stl_io = { version = "0.8.3", optional = true }
contour_tracing = { version = "1.0.12", features = ["array"], optional = true }
fast-surface-nets = { version = "0.2.1", optional = true }
hashbrown = { version = "0.15.2", optional = true }

[features]
default = ["f64", "stl-io", "dxf-io", "chull-io", "metaballs", "hashmap", "sdf", "offset"]
parallel = [
    "rayon",
    "geo/multithreading",
]
f64 = [
  "rapier3d-f64",
  "parry3d-f64",
]
f32 = [
  "rapier3d",
  "parry3d",
]
chull-io = [ # convex hull and minkowski sum
  "chull",
]
stl-io = [
  "stl_io",
]
dxf-io = [
  "dxf",
]
metaballs = [
  "fast-surface-nets",
]
hashmap = [ # slice and related helper functions, is_manifold()
  "hashbrown",
]
sdf = [
  "fast-surface-nets",
]
offset = [
  "geo-buf",
]
